---
title: "README"
author: "Jeff Wesner"
format: html
editor: visual
editor_options: 
  markdown: 
    wrap: 72
---

## isdbayes

Fit hierarchical Bayesian models to body size spectra data using the
truncated pareto described here:
<https://www.biorxiv.org/content/10.1101/2023.02.14.528491v1>.

```{r}
# knitr::opts_chunk$set(eval = FALSE)
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(brms) 
library(here) 
library(tidyverse) 
source(here("R/brm_distributions.R"))
```

```{r}
lambda = -1.2 # lambda value 
xmin = 1 # minimum size 
xmax = 1000 # maximum size

sim_data = tibble(x = rparetocounts(n = 100, 
                                    mu = lambda, # use brms terminology
                                    vreal2 = xmin, 
                                    vreal3 = xmax)) %>% 
  mutate(xmin = xmin, xmax = xmax) %>% 
  group_by(x) %>% 
  add_count(name = "counts") # column for density of each body size

fit = brm(x | vreal(counts, xmin, xmax) ~ 1, 
          family = paretocounts, 
          data = sim_data, 
          stanvars = stanvars,
          prior = c(prior(normal(-1.2, 0.2), class = "Intercept")))

```

## Fit multiple size spectra with linear predictors

```{r}
lambda = -1.2 # lambda value 
xmin = 1 # minimum size 
xmax = 1000 # maximum size

sim_data = tibble(x = rparetocounts(n = 300, 
                                    mu = lambda, # use brms terminology
                                    vreal2 = xmin, 
                                    vreal3 = xmax)) %>% 
  mutate(xmin = xmin, xmax = xmax) %>% 
  group_by(x) %>% 
  add_count(name = "counts") %>% # column for density of each body size
  expand_grid(group = c("a", "b", "c"))

fit = brm(x | vreal(counts, xmin, xmax) ~ 1 + group, 
          family = paretocounts, 
          data = sim_data,
          stanvars = stanvars,
          prior = c(prior(normal(-1.2, 0.2), class = "Intercept"),
                    prior(normal(0, 0.1), class = "b")))
```
